CREATE TABLE IF NOT EXISTS Users (
    id INTEGER NOT NULL AUTO_INCREMENT,
    nickname VARCHAR(16) NOT NULL UNIQUE,
    email VARCHAR(128) NOT NULL UNIQUE,
    profileDescription VARCHAR(1024) DEFAULT NULL,
    profilePicture MEDIUMBLOB DEFAULT NULL,
    provider ENUM('spotify', 'google') NOT NULL,
    premiumAccount BOOLEAN DEFAULT NULL,
    providerLoginID VARCHAR(256) NOT NULL,
    acessToken VARCHAR(1024) NOT NULL UNIQUE,
    refreshToken VARCHAR(1024) NOT NULL UNIQUE,
    tokenExpireAt TIMESTAMP NOT NULL UNIQUE,
    pushToken VARCHAR(4096) NOT NULL UNIQUE,
    PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Groups (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    maxUsers TINYINT UNSIGNED DEFAULT 4 NOT NULL,
    notifNB TINYINT UNSIGNED DEFAULT NULL,
    groupPicture MEDIUMBLOB DEFAULT NULL,
    choosenOneUserID INTEGER DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (choosenOneUserID) REFERENCES Users(id),
    CONSTRAINT nbUsers CHECK (maxUsers >= 2)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS GroupsUsers (
    groupID INTEGER NOT NULL,
    userID INTEGER NOT NULL,
    notifPending BOOLEAN DEFAULT NULL,
    weeklyScore INTEGER UNSIGNED DEFAULT 0,
    globalScore INTEGER UNSIGNED DEFAULT 0,
    PRIMARY KEY (groupID, userID),
    FOREIGN KEY (groupID) REFERENCES Groups(id),
    FOREIGN KEY (userID) REFERENCES Users(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Tracks (
    id INTEGER NOT NULL AUTO_INCREMENT,
    title VARCHAR(128) NOT NULL,
    artist VARCHAR(32) NOT NULL,
    ISRC VARCHAR(16) DEFAULT NULL,
    youtubeLink VARCHAR(128) DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS GroupsPlaylists (
    groupID INTEGER NOT NULL,
    trackID INTEGER NOT NULL,
    userID INTEGER NOT NULL,
    addedAt TIMESTAMP NOT NULL,
    PRIMARY KEY (groupID, trackID, userID),
    FOREIGN KEY (groupID) REFERENCES Groups(id),
    FOREIGN KEY (trackID) REFERENCES Tracks(id),
    FOREIGN KEY (userID) REFERENCES Users(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS RealRanking (
    groupID INTEGER NOT NULL,
    trackID INTEGER NOT NULL,
    userID INTEGER NOT NULL,
    rank TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY (groupID, trackID, userID),
    FOREIGN KEY (groupID) REFERENCES Groups(id),
    FOREIGN KEY (trackID) REFERENCES Tracks(id),
    FOREIGN KEY (userID) REFERENCES Users(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PredictingRanking (
    groupID INTEGER NOT NULL,
    trackID INTEGER NOT NULL,
    userID INTEGER NOT NULL,
    oracleUserID INTEGER NOT NULL,
    rank TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY (groupID, trackID, userID),
    FOREIGN KEY (groupID) REFERENCES Groups(id),
    FOREIGN KEY (trackID) REFERENCES Tracks(id),
    FOREIGN KEY (userID) REFERENCES Users(id),
    FOREIGN KEY (oracleUserID) REFERENCES Users(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Invitations (
    id INTEGER AUTO_INCREMENT NOT NULL,
    createdBy INTEGER NOT NULL,
    groupID INTEGER NOT NULL,
    token VARCHAR(1024) NOT NULL UNIQUE,
    expiresAt TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (groupID) REFERENCES Groups(id),
    FOREIGN KEY (createdBy) REFERENCES Users(id)
) ENGINE=InnoDB;